In [1]:
import pandas as pd

from faker import Faker
from faker.providers import DynamicProvider
import pandas as pd
import random
from faker import Faker
from random import randrange
from datetime import datetime
import numpy as np
from random import randint 
%matplotlib inline

In [2]:
data = pd.read_csv('perfume_data_final.csv')

In [3]:
data['clstotal']=data['clswinter']+data['clsspring']+data['clssummer']+data['clsautumn']
data['clswinter']=data['clswinter']/data['clstotal']
data['clsspring']=data['clsspring']/data['clstotal']
data['clssummer']=data['clssummer']/data['clstotal']
data['clsautumn']=data['clsautumn']/data['clstotal']
data.drop(columns=['clstotal'],  inplace= True)

In [4]:
data['clstotal']=data['clsday']+data['clsnight']
data['clsday']=data['clsday']/data['clstotal']
data['clsnight']=data['clsnight']/data['clstotal']
data.drop(columns=['clstotal'],  inplace= True)


In [5]:
data['clstotal']=data['clswinter']+data['clsspring']+data['clssummer']+data['clsautumn']

In [6]:
data['female25under']=data['clslove_female25under']+data['clslike_female25under']
data['male25under']=data['clslove_male25under']+data['clslike_male25under']
data['female25older']=data['clslove_female25older']+data['clslike_female25older']
data['male25older']=data['clslove_male25older']+data['clslike_male25older']


In [7]:
data['sillage']= (10*data['sillage_soft']+20*data['sillage_moderate']+30*data['sillage_heavy']+40*data['sillage_enormous'])/100

In [8]:
data.drop(columns=[  'date','title','clslove_female25under',
       'clslove_male25under', 'clslove_female25older', 'clslove_male25older',
       'clslike_female25under', 'clslike_male25under', 'clslike_female25older',
       'clslike_male25older', 'clsdislike_female25under',
       'clsdislike_male25under', 'clsdislike_female25older',
       'clsdislike_male25older', 'clswinter_female25under',
       'clswinter_male25under', 'clswinter_female25older',
       'clswinter_male25older', 'clsspring_female25under',
       'clsspring_male25under', 'clsspring_female25older',
       'clsspring_male25older', 'clssummer_female25under',
       'clssummer_male25under', 'clssummer_female25older',
       'clssummer_male25older', 'clsautumn_female25under',
       'clsautumn_male25under', 'clsautumn_female25older',
       'clsautumn_male25older', 'clsday_female25under', 'clsday_male25under',
       'clsday_female25older', 'clsday_male25older', 'clsnight_female25under',
       'clsnight_male25under', 'clsnight_female25older',
       'clsnight_male25older','accords_2','accords_3','rating_score','votes','longevity_poor',
       'longevity_weak', 'longevity_moderate', 'longevity_long',
       'longevity_very_long','sillage_soft', 'sillage_moderate',
       'sillage_heavy', 'sillage_enormous','clscold', 'clshot','clstotal','gender','notes_1', 'notes_2', 'notes_3','brand','accords_1'], inplace=True)

In [9]:
# drop_colum_list=['accords_1']              # enter column values here
# data.dropna(subset=drop_colum_list,inplace=True)
# data.reset_index(drop=True,inplace=True) 

In [10]:
data[['clswinter','clsspring','clssummer','clsautumn']] = pd.DataFrame(np.where(data[['clswinter','clsspring','clssummer','clsautumn']].T == data[['clswinter','clsspring','clssummer','clsautumn']].T.max(), 1, 0),index=['clswinter','clsspring','clssummer','clsautumn']).T

In [11]:
data[['clsday','clsnight']] = pd.DataFrame(np.where(data[['clsday','clsnight']].T == data[['clsday','clsnight']].T.max(), 1, 0),index=['clsday','clsnight']).T

In [12]:
data[['Ihaveit', 'Ihadit','Iwantit']] = pd.DataFrame(np.where(data[['Ihaveit', 'Ihadit','Iwantit']].T == data[['Ihaveit', 'Ihadit','Iwantit']].T.max(), 1, 0),index=['Ihaveit', 'Ihadit','Iwantit']).T

In [13]:
data[['female25under','male25under', 'female25older', 'male25older']] = pd.DataFrame(np.where(data[['female25under','male25under', 'female25older', 'male25older']].T == data[['female25under','male25under', 'female25older', 'male25older']].T.max(), 1, 0),index=['female25under','male25under', 'female25older', 'male25older']).T

In [14]:
import warnings
warnings.filterwarnings("ignore")
for i in range(len(data)): 
    if(data['female25under'][i]+data['male25under'][i]+data['female25older'][i]+data['male25older'][i]==4):
        data['female25under'][i]=1
        data['male25under'][i]=0
        data['female25older'][i]=0
        data['male25older'][i]=0
    elif(data['female25under'][i]+data['male25under'][i]+data['female25older'][i]+data['male25older'][i]==3):
        data['female25under'][i]=0
        data['male25under'][i]=1
        data['female25older'][i]=0
        data['male25older'][i]=0
    elif(data['female25under'][i]+data['male25under'][i]+data['female25older'][i]+data['male25older'][i]==2):
        data['female25under'][i]=0
        data['male25under'][i]=0
        data['female25older'][i]=1
        data['male25older'][i]=0

In [15]:
# fake = Faker()
# Faker.seed(0)
# feeling_list=['joy',
# 'confident',
# 'sensual',
# 'calm',
# 'happy',
# 'optimistic',
# 'uplifting',
# 'relaxation',
# 'romantic',
# 'sheer',
# 'positivity',
# 'energized',
# 'happiness',
# 'positive',
# 'cheerful',
# 'sensuousness',
# 'carefree',
# 'feminine',
# 'spirited',
# 'irreverent',
# 'memorable',
# 'shimmering']
# data['feeling1']=''
# data['feeling2']=''
# data['feeling3']=''
# feeling_provider = DynamicProvider(provider_name="feeling",   
#                                         elements=feeling_list,)
# fake.add_provider(feeling_provider)

# for i in range(len(data)):
#     feel1 = fake.feeling()
#     feel2 = fake.feeling()
#     feel3 = fake.feeling()
#     data.loc[i, 'feeling1'] = feel1
#     data.loc[i, 'feeling2'] = feel2
#     data.loc[i, 'feeling3'] = feel3
# data.head(5)    

In [16]:
fake = Faker()
Faker.seed(0)
feeling_list=['joy',
'confident',
'sensual',
'calm',
'happy',
'optimistic',
'uplifting',
'relaxation',
'romantic',
'sheer',
'positivity',
'energized',
'happiness',
'positive',
'cheerful',
'sensuousness',
'carefree',
'feminine',
'spirited',
'irreverent',
'memorable',
'shimmering', ]
data['feeling']=data.apply(lambda x: [], axis=1)

feeling_provider = DynamicProvider(provider_name="feeling",   
                                        elements=feeling_list,)
fake.add_provider(feeling_provider)

for i in range(len(data)):
    feel1 = fake.feeling()
    feel2 = fake.feeling()
    feel3 = fake.feeling()
    data.loc[i, 'feeling'].extend([feel1,feel2,feel3])
data.head(5)    

longevity  clswinter  clsspring  clssummer  clsautumn  clsday  clsnight  \
0          3          1          1          1          1       1         1   
1          6          1          0          0          0       1         1   
2          0          1          1          1          1       1         1   
3          0          0          1          1          1       1         1   
4          2          1          1          1          1       1         1   

   Ihaveit  Ihadit  Iwantit  female25under  male25under  female25older  \
0        1       0        0              0            0              0   
1        1       0        0              0            0              1   
2        0       0        1              1            0              0   
3        0       0        1              1            0              0   
4        0       0        1              1            0              0   

   male25older  sillage                             feeling  
0            1      1.4    [happiness, positive, confident]  
1            0      2.1  [romantic, carefree, sensuousness]  
2            0      0.0    [happiness, sheer, sensuousness]  
3            0      0.0    [energized, spirited, uplifting]  
4            0      0.4            [carefree, happy, sheer]

In [17]:
fake = Faker()
Faker.seed(0)
fragrance_list=['Tender Light',
'Desert Eden',
'Infinite Sky',
'Sensuous Stars',
'Paradise Moon',
'Radiant Mirage',
'Dream Dusk',
'Blushing Sands',
'Beautiful Magnolia',
'Modern Muse',
'Beautiful Belle',
'Beautiful',
'Estée Lauder Pleasures',
'Amber Mystique',
'Cinnabar',
'SpellBound']

data['fragrance']=data.apply(lambda x: [], axis=1)

fragrance_provider = DynamicProvider(provider_name="fragrance",   
                                        elements=fragrance_list,)
fake.add_provider(fragrance_provider)

for i in range(len(data)):
    frag1 = fake.fragrance()
    frag2 = fake.fragrance()
    frag3 = fake.fragrance()
    data.loc[i, 'fragrance'].extend([frag1,frag2,frag2])
data.head(5)    

longevity  clswinter  clsspring  clssummer  clsautumn  clsday  clsnight  \
0          3          1          1          1          1       1         1   
1          6          1          0          0          0       1         1   
2          0          1          1          1          1       1         1   
3          0          0          1          1          1       1         1   
4          2          1          1          1          1       1         1   

   Ihaveit  Ihadit  Iwantit  female25under  male25under  female25older  \
0        1       0        0              0            0              0   
1        1       0        0              0            0              1   
2        0       0        1              1            0              0   
3        0       0        1              1            0              0   
4        0       0        1              1            0              0   

   male25older  sillage                             feeling  \
0            1      1.4    [happiness, positive, confident]   
1            0      2.1  [romantic, carefree, sensuousness]   
2            0      0.0    [happiness, sheer, sensuousness]   
3            0      0.0    [energized, spirited, uplifting]   
4            0      0.4            [carefree, happy, sheer]   

                                           fragrance  
0  [Estée Lauder Pleasures, Amber Mystique, Amber...  
1       [Beautiful Magnolia, SpellBound, SpellBound]  
2              [Modern Muse, SpellBound, SpellBound]  
3         [Dream Dusk, Paradise Moon, Paradise Moon]  
4    [Paradise Moon, Sensuous Stars, Sensuous Stars]

In [18]:
# fake = Faker()
# Faker.seed(0)
# fragrance_list=['Chinese Tea',
# 'Sandalwood',
# 'Amber',
# 'Chinese Plum',
# 'Osmanthus',
# 'Sandalwood',
# 'Cherry Blossom',
# 'Vetiver',
# 'Magnolia',
# 'florals',
# 'Lychee',
# 'Rose',
# 'White Lily']
# data['fragrance']=''

# fragrance_provider = DynamicProvider(provider_name="fragrance",   
#                                         elements=fragrance_list,)
# fake.add_provider(fragrance_provider)

# for i in range(len(data)):
#     fragrance = fake.fragrance()
#     data.loc[i, 'fragrance'] = fragrance
# data.head(5)    

In [19]:
data.columns

Index(['longevity', 'clswinter', 'clsspring', 'clssummer', 'clsautumn',
       'clsday', 'clsnight', 'Ihaveit', 'Ihadit', 'Iwantit', 'female25under',
       'male25under', 'female25older', 'male25older', 'sillage', 'feeling',
       'fragrance'],
      dtype='object')

In [20]:
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()
data = data.join(pd.DataFrame(mlb.fit_transform(data.pop('feeling')),
                          columns=mlb.classes_,
                          index=data.index))

mlb = MultiLabelBinarizer()
data = data.join(pd.DataFrame(mlb.fit_transform(data.pop('fragrance')),
                          columns=mlb.classes_,
                          index=data.index))

In [21]:
['Tender Light',
'Desert Eden',
'Infinite Sky',
'Sensuous Stars',
'Paradise Moon',
'Radiant Mirage',
'Dream Dusk',
'Blushing Sands',
'Beautiful Magnolia',
'Modern Muse',
'Beautiful Belle',
'Beautiful',
'Estée Lauder Pleasures',
'Amber Mystique',
'Cinnabar',
'SpellBound']

['Tender Light',
 'Desert Eden',
 'Infinite Sky',
 'Sensuous Stars',
 'Paradise Moon',
 'Radiant Mirage',
 'Dream Dusk',
 'Blushing Sands',
 'Beautiful Magnolia',
 'Modern Muse',
 'Beautiful Belle',
 'Beautiful',
 'Estée Lauder Pleasures',
 'Amber Mystique',
 'Cinnabar',
 'SpellBound']

In [22]:
data.columns 

Index(['longevity', 'clswinter', 'clsspring', 'clssummer', 'clsautumn',
       'clsday', 'clsnight', 'Ihaveit', 'Ihadit', 'Iwantit', 'female25under',
       'male25under', 'female25older', 'male25older', 'sillage', 'calm',
       'carefree', 'cheerful', 'confident', 'energized', 'feminine',
       'happiness', 'happy', 'irreverent', 'joy', 'memorable', 'optimistic',
       'positive', 'positivity', 'relaxation', 'romantic', 'sensual',
       'sensuousness', 'sheer', 'shimmering', 'spirited', 'uplifting',
       'Amber Mystique', 'Beautiful', 'Beautiful Belle', 'Beautiful Magnolia',
       'Blushing Sands', 'Cinnabar', 'Desert Eden', 'Dream Dusk',
       'Estée Lauder Pleasures', 'Infinite Sky', 'Modern Muse',
       'Paradise Moon', 'Radiant Mirage', 'Sensuous Stars', 'SpellBound',
       'Tender Light'],
      dtype='object')

In [23]:

import numpy as np
import pylab as pl
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
from sklearn.utils import shuffle
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import cross_val_score, GridSearchCV
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

In [24]:
# from sklearn import preprocessing
# encoder = preprocessing.LabelEncoder()

In [25]:
# encoder.fit(data['fragrance'])
# Y_train = encoder.transform(data['fragrance'])

In [26]:
target_columns=['Tender Light',
'Desert Eden',
'Infinite Sky',
'Sensuous Stars',
'Paradise Moon',
'Radiant Mirage',
'Dream Dusk',
'Blushing Sands',
'Beautiful Magnolia',
'Modern Muse',
'Beautiful Belle',
'Beautiful',
'Estée Lauder Pleasures',
'Amber Mystique',
'Cinnabar',
'SpellBound']
x=data.drop(columns=target_columns)
y=data[target_columns]

train = data.iloc[:45000]
test = data.iloc[45000:]



xtrain=x.iloc[:45000]
ytrain=y.iloc[:45000]

xtest=x.iloc[45000:]
ytest=y.iloc[45000:]

In [27]:

import numpy as np
import pandas as pd
from xgboost.sklearn import XGBClassifier
from sklearn.metrics import confusion_matrix


clf = XGBClassifier(max_depth=7, n_estimators=1000,
                   # objective='multi:softmax',num_class=13
                   )

model=clf.fit(xtrain, ytrain)


In [28]:
import pickle
filename = 'global.pkl'
pickle.dump(model, open(filename, 'wb'))

# # to load the saved model
# bst = pickle.load(open(filename, 'rb'))

In [29]:
n = 3
probas =  clf.predict_proba(xtest)
top_n_lables_idx = np.argsort(-probas)[:, :n]
top_n_probs = np.round(-np.sort(-probas),3)[:, :n]
colum_list=model.get_booster().feature_names
print(top_n_lables_idx)
print(top_n_probs)
top_n_labels = [colum_list[i] for i in top_n_lables_idx]

results = list(zip(top_n_labels, top_n_probs))

pd.DataFrame(results)

[[ 9  3  5]
 [ 4  6 15]
 [ 0 13  4]
 ...
 [ 9 12  6]
 [ 0  2 13]
 [10 15  9]]
[[0.571 0.166 0.149]
 [0.23  0.184 0.123]
 [0.904 0.799 0.251]
 ...
 [0.378 0.327 0.197]
 [0.243 0.232 0.193]
 [0.289 0.168 0.168]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
[colum_list[i] for i in top_n_lables_idx]

In [ ]:
[l.tolist() for l in top_n_lables_idx]

[i for i in l.tolist() for l in top_n_lables_idx ]

In [ ]:
top_n_lables_idx

In [ ]:
top_n_probs